Repository doroshtm/e-commerce, pull requests merged in 2023-10, with the labels that each got.

#30 Pesquisa e filtro funcionando. Passíveis de alteração.
  website/cadastro.php
  website/contato.php
  website/estatisticas.html
  website/index.php
  website/js/cadastro.js
  website/js/produtos.js
  website/js/script_produtos.js
  website/login.php
  website/produtos.php
  website/sobre.php
Labels: enhancement

#33 SQL alterado para seguir boas práticas
  website/cadastro.php
  website/login.php
Labels: enhancement

#40 Arrumada tela de produtos
  website/produtos.php
Labels: fixed

#44 Adicionada tela de cadastro de produtos
  website/cadastro.php
  website/cadastro_produto.php
  website/carrinho.php
  website/login.php
  website/sobre.php
Labels: enhancement

#45 Cadastro de produtos funcionando
  website/cadastro.php
  website/cadastro_produto.php
  website/produtos.php
Labels: enhancement

#46 Melhorada experiência do usuário ao cadastrar, logar e deslogar
  website/cadastro.php
  website/cadastro_produto.php
  website/carrinho.php
  website/contato.php
  website/imagens/logout.jpg
  website/index.php
  website/login.php
  website/logout.php
  website/produtos.php
  website/sobre.php
  website/util.php
Labels: enhancement

#48 Corrigido estilos
  website/cadastro.php
  website/imagens/logout.svg
  website/login.php
  website/styles_header_footer.css
  website/util.php
Labels: enhancement, fixed

#49 Adicionada função de ordenar produtos
  website/imagens/seta_baixo.jpg
  website/imagens/seta_cima.jpeg
  website/js/produtos.js
  website/produtos.php
  website/styles_header_footer.css
Labels: enhancement

#50 Alteração de produtos funcionando
  website/alteracao_produto.php
  website/cadastro.php
  website/cadastro_produto.php
  website/carrinho.html
  website/carrinho.php
  website/contato.php
  website/demonstracao.html
  website/esqueci.php
  website/imagens/editar.png
  website/index.php
  website/login.php
  website/produtos.php
  website/sobre.php
Labels: enhancement

#52 Consertada página de remoção de produtos, melhorada página de alteração de produtos
  website/alteracao_produto.php
  website/remocao_produto.php
Labels: enhancement, fixed

#53 Resolvida uma série de bugs
  website/alteracao_produto.php
  website/cadastro.php
  website/cadastro_produto.php
  website/debug/camarao.html
  website/debug/login.html
  website/imagens/Aumentar_qtd_azul.svg
  website/imagens/adicionar.svg
  website/imagens/carrinho.svg
  website/imagens/user_icon.svg
  website/js/produtos.js
  website/login.php
  website/produtos.php
  website/styles_header_footer.css
Labels: fixed

#54 Crud de usuários feito. Tela de usuários iniciada.
  website/imagens/remover.jpg
  website/usuario.php
  website/util.php
Labels: enhancement

#55 Alteradas páginas de produtos e cadastro
  website/alteracao_produto.php
  website/cadastro.php
  website/cadastro_produto.php
  website/imagens/Seta-dropdown-cima.svg
  website/styles_header_footer.css
Labels: enhancement

#56 Terminados estilos para administrador
  website/cadastro_produto.php
  website/carrinho.html
  website/carrinho.php
  website/contato.php
  website/imagens/sort-down.svg
  website/imagens/sort-up.svg
  website/imagens/sort_down.svg
  website/imagens/sort_up.svg
  website/index.php
  website/js/produtos.js
  website/produtos.php
  website/sobre.php
  website/styles_header_footer.css
  website/usuario.php
  website/util.php
Labels: enhancement, fixed

#57 Iniciada alteração no sistema de remoção e restauração de produto
  website/alteracao_produto.php
  website/produtos.php
  website/remocao_produto.php
  website/styles_header_footer.css
Labels: bug, enhancement

#58 Adicionadas verificações de segurança; melhorada função header_pag; remoção e restauração de produtos funcionando
  website/alteracao_produto.php
  website/cadastro.php
  website/cadastro_produto.php
  website/carrinho.php
  website/contato.php
  website/imagens/logout.jpg
  website/imagens/seta_baixo.jpg
  website/imagens/seta_cima.jpeg
  website/imagens/sort-down.svg
  website/imagens/sort-up.svg
  website/index.php
  website/produtos.php
  website/remocao_produto.php
  website/sobre.php
  website/styles_header_footer.css
  website/usuario.php
  website/usuarios.php
  website/util.php
Labels: enhancement, fixed

#60 Melhorada responsividade tabela usuário
  website/styles_header_footer.css
  website/usuarios.php
Labels: enhancement, fixed

#61 Atualizado código de cálculo da margem de lucro (adicionado round)
  website/alteracao_produto.php
  website/cadastro_produto.php
Labels: fixed

#62 Adicionadas verificações no 'alteracao_produto.php' e código de alteração e cadastro de produtos melhorados como um todo
  website/alteracao_produto.php
  website/alteracao_usuario.php
  website/cadastro.php
  website/cadastro_produto.php
  website/login.php
  website/usuarios.php
Labels: enhancement, fixed

#63 Alteração de usuários funcionando; variáveis alteradas para inglês
  website/alteracao_produto.php
  website/alteracao_usuario.php
  website/cadastro.php
  website/cadastro_produto.php
  website/login.php
  website/produtos.php
  website/remocao_produto.php
Labels: enhancement

#65 Consertada verificação de imagem em 'alteracao_produto.php' e 'cadastro_produto.php'
  website/alteracao_produto.php
  website/alteracao_usuario.php
  website/cadastro_produto.php
  website/login.php
  website/produtos.php
Labels: enhancement, fixed

#66 Alterações no cadastro e na tela de produtos
  website/cadastro.php
  website/js/cadastro.js
  website/login.php
  website/produtos.php
  website/util.php
Labels: enhancement, fixed

#67 Carrinho iniciado
  database/ecommerce_tables.sql
  website/alteracao_produto.php
  website/alteracao_usuario.php
  website/cadastro.php
  website/cadastro_produto.php
  website/carrinho.php
  website/contato.php
  website/index.php
  website/js/carrinho.js
  website/login.php
  website/produtos.php
  website/remocao_produto.php
  website/remocao_usuario.php
  website/sobre.php
  website/usuarios.php
  website/util.php
Labels: enhancement

#69 Corrigido bug na compra
  website/cadastro.php
  website/carrinho.php
  website/compra.php
  website/login.php
  website/produtos.php
  website/styles_header_footer.css
  website/util.php
Labels: fixed

#70 Melhoras no carrinho e na compra
  database/ecommerce_tables.sql
  website/cadastro.php
  website/carrinho.php
  website/compra.php
  website/login.php
  website/produtos.php
Labels: enhancement, fixed

#72 Corrigida falta de lógica em 'carrinho.php'
  website/carrinho.php
Labels: fixed

#73 Função de manter usuário conectado funcionando corretamente
  database/ecommerce_tables.sql
  website/cadastro.php
  website/carrinho.html
  website/login.php
  website/util.php
Labels: fixed

#74 Carrinho agora mostra se usuário não tem produtos
  website/carrinho.php
Labels: enhancement

#75 Melhorado estilos de administrador
  website/alteracao_produto.php
  website/cadastro.php
  website/carrinho.php
  website/debug/camarao.html
  website/demonstracao.html
  website/imagens/Aumentar_qtd.svg
  website/imagens/Diminuir_qtd.svg
  website/imagens/remover.svg
  website/js/alterar.js
  website/login.php
  website/produtos.php
  website/styles_header_footer.css
  website/usuarios.php
Labels: enhancement, fixed

#76 Alterada alteração de produtos
  website/alteracao_produto.php
  website/produtos.php
Labels: enhancement

#81 Correção de bugs referentes o carrinho
  website/carrinho.php
  website/compra.php
Labels: fixed

#82 Feita landing page
  website/carrinho.php
  website/demonstracao.html
  website/imagens/CTI_chaveiro_2-transformed.jpg
  website/imagens/Mecânica_2.jpg
  website/imagens/Rendereureka.png
  website/imagens/Renderjussara.png
  website/imagens/Renderlobo.png
  website/imagens/Renderpython.png
  website/imagens/Rendertouro.png
  website/imagens/cti.png
  website/imagens/cti_sticker.png
  website/imagens/elet.png
  website/imagens/gatoCTI.png
  website/imagens/info.png
  website/imagens/mec.png
  website/imagens/rendercti.png
  website/imagens/renderglitch.png
  website/index.php
  website/js/home.js
  website/styles_header_footer.css
Labels: enhancement

#83 Responsividade home e abreviações
  website/alteracao_produto.php
  website/js/produtos.js
  website/js/sobre.js
  website/js/util.js
  website/produtos.php
  website/sobre.php
  website/styles_header_footer.css
  website/util.php
Labels: enhancement, fixed

#87 Mudança no carrinho
  website/styles_header_footer.css
Labels: fixed

#88 Série de alterações para seguir os novos padrões
  website/alteracao_produto.php
  website/alteracao_usuario.php
  website/cadastro.php
  website/cadastro_produto.php
  website/carrinho.php
  website/compra.php
  website/contato.php
  website/index.php
  website/js/carrinho.js
  website/login.php
  website/logout.php
  website/produtos.php
  website/remocao_produto.php
  website/remocao_usuario.php
  website/sobre.php
  website/usuarios.php
  website/util.php
Labels: fixed

#89 Consertada tela de compra de produtos
  website/compra.php
  website/js/compra.js
  website/util.php
Labels: invalid, fixed

#92 Série de alterações durante o primeiro dia de vendas
  website/carrinho.php
  website/index.php
  website/js/home.js
  website/js/produtos.js
  website/produtos.php
  website/sobre.php
  website/util.php
Labels: enhancement

#93 Alterações durante a semana do colégio
  website/alteracao_produto.php
  website/cadastro_produto.php
  website/produtos.php
  website/styles_header_footer.css
Labels: fixed

#94 Esqueci a senha e persistência de sessões
  .gitignore
  .gitmodules
  database/ecommerce_tables.sql
  website/alteracao_produto.php
  website/alteracao_usuario.php
  website/cadastro.php
  website/cadastro_produto.php
  website/carrinho.php
  website/compra.php
  website/contato.php
  website/esqueci.php
  website/index.php
  website/login.php
  website/produtos.php
  website/recuperacao_senha.php
  website/remocao_produto.php
  website/remocao_usuario.php
  website/sobre.php
  website/usuarios.php
  website/util.php
Labels: enhancement, fixed

#95 Visual do esqueci a senha e remoção/restauração de produtos arrumados
  website/alteracao_produto.php
  website/carrinho.php
  website/esqueci.php
  website/index.php
  website/login.php
  website/produtos.php
  website/recuperacao_senha.php
  website/remocao_produto.php
  website/styles_header_footer.css
  website/styles_paginas.css
Labels: fixed

#96 Alterações front-end durante o Viva CTI e deletado cabecalho.php
  website/alteracao_produto.php
  website/cabecalho.php
  website/cadastro_produto.php
  website/imagens/20231017_073810.jpg
  website/imagens/20231017_073847.jpg
  website/imagens/20231017_073936.jpg
  website/imagens/20231017_074055.jpg
  website/imagens/Cti1.jpg
  website/imagens/Cti2.jpg
  website/imagens/Eletro1.jpg
  website/imagens/Eletro2.jpg
  website/imagens/Info1.jpg
  website/imagens/Info2.jpg
  website/imagens/Mec1.jpg
  website/imagens/Mec2.jpg
  website/index.php
  website/styles_header_footer.css
Labels: enhancement
