Repository doroshtm/e-commerce, pull requests merged in 2023-11, with the labels that each got.

#97 Modificado filtro do home
  website/js/produtos.js
  website/produtos.php
  website/styles_header_footer.css
Labels: enhancement, fixed

#99 Finalizada tela de produto individual
  website/produto.php
  website/produtos.php
  website/styles_header_footer.css
Labels: enhancement, fixed

#101 Consertados pequenos problemas
  website/alteracao_produto.php
  website/alteracao_usuario.php
  website/compra.php
Labels: fixed

#102 Mudanças finais
  website/alteracao_produto.php
  website/alteracao_usuario.php
  website/cadastro_produto.php
  website/carrinho.php
  website/contato.php
  website/index.php
  website/produtos.php
  website/remocao_usuario.php
  website/sobre.php
  website/styles_header_footer.css
  website/usuarios.php
Labels: enhancement, fixed

#104 Melhoras de design no produto.php
  website/produto.php
  website/styles_header_footer.css
Labels: enhancement

#105 Finalizado 'relatorio.php' (e o e-commerce)
  website/FPDF/FAQ.htm
  website/FPDF/changelog.htm
  website/FPDF/html_table.php
  website/debug/cadastro.html
  website/debug/camarao.html
  website/debug/debug.html
  website/debug/index.html
  website/debug/login.html
  website/debug/script.js
  website/debug/sobre.html
  website/debug/styles.css
  website/js/produtos.js
  website/produtos.php
  website/relatorio.php
  website/remocao_usuario.php
  website/usuarios.php
  website/util.php
Labels: enhancement

#106 Alterado relatório para seguir pedidos do Cabello
  website/js/relatorio.js
  website/relatorio.php
  website/usuarios.php
Labels: fixed

#109 Última alteração no relatório (agora, os relatórios não são sobrescritos)
  website/relatorio.php
Labels: fixed

#110 Update relatorio.php
  website/relatorio.php
Labels: fixed
